services: docker

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - os: osx
      env:
        - C_COMPILER=clang-8 CXX_COMPILER=clang++-8

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803

sudo: required

language:
  - cpp

addons:
  apt:
    packages:
      - qt5
  homebrew:
    packages:
      - qt5


script:
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
  - cmake --build . --target nxi --config Release
