services: docker
language: cpp
sudo: required

env:
  global:
    - RELEASE_FILENAME=release_${TRAVIS_TAG}_${TRAVIS_OS_NAME}.7z

matrix:
  include:
  - os: linux
    env:
      - CC=gcc-8 CXX=g++-8
      - QT_PATH=/5.13.1/gcc_64
    before_install:
    - docker build -t nxi_image ./ci
    script:
    - docker run --name nxi -w /nxi -v `pwd`:/nxi nxi_image
            bash -c "
                mkdir build && cd build &&
                cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DNXI_QT_ROOT=${QT_PATH} -DSTZ_FILESYSTEM=ON .. &&
                cmake --build . --target nxi --config Release &&
                cd .. &&
                7z a -r ${RELEASE_FILENAME} ./bin/*
            "
    deploy:
      provider: releases
      api_key:
        secure: S2FAka4xQ6VMZnakdnfeBLHUqcefnHIAhnpnNuZi/3iOwDTGDHm6CbVf2LHhowRjY+5k2QcH7FiQQqC9aZYg556loC+0MnhO7WwDZbLpFJlhc86vI1howSdse+w/6VNE1bVCqQomDrVvNXKgQ3NHC74mDXV1vk8jCCpXqxJPpFVtifLcvlKCIqRH8C6pa7yFFxElTS392lpeX+WXcG15FUsmqXTDUD9MST+vCh31zxuBNRSrOBxcC/u7ZkFl74K9y0Qtqdk0nvCruMMI1ddkVfQhYS2cmfvvViRAng5QdJT+9SqwKNpVi9amdNjK8NJXgqCxrAqX1YqufRL1LLXTYiOnLsztfSLDJQYGjWtyl13Hcrc85B4cyXe8tjRBUa1iIWFQjH84GcJwKFHCfE9rFz2f0w9PrvooHeibZmYucpF8Bu3UX7sPvU3iSGNFMX1j74srwBQwdQBDhEbMUroSr8WASsXaD7kw1AJdTO26fAEJUopS0OB2o7h4ULBrs+Ud3jCu1QcGYdVX5J6mjRMDyO6f7mgcF9tZiSH9oIvQI6L2n+JRYRCmRoWYHxYMke86g0yRuaq+ltTAvcCsXp8Trzc1S72F3Vm3NxWhAOpJ8tCiECOFGarW5GUpS4rnw38kEbBmlwtYf8f9B+LpOuuf37/q7y+Lflh1heMAg0x3B2Y=
      file: ${RELEASE_FILENAME}
      skip_cleanup: true
      on:
        tags: true
        all_branches: true

  # --ignore-package-exit-codes ignore error on reboot
  # VS2019 16.3.10 https://docs.microsoft.com/en-us/visualstudio/releases/2019/history // https://download.visualstudio.microsoft.com/download/pr/5446351f-19f5-4b09-98c6-a4bfacc732d7/3cec278012466e87b76be170de3f881e3c14be52bf8eaa3b8c464dbeee3b4fef/vs_BuildTools.exe
  - os: windows
    dist: 1803-containers
    env:
      - QT_VERSION=5.13.1
      - VERSION=1.11 VARIANT=windows/windowsservercore-1803
      - PATH="${PATH}:${TRAVIS_BUILD_DIR}/${QT_VERSION}/msvc2017_64/bin:${TRAVIS_BUILD_DIR}/${QT_VERSION}/msvc2017_64"
    script:
      - choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - curl https://download.visualstudio.microsoft.com/download/pr/5446351f-19f5-4b09-98c6-a4bfacc732d7/3cec278012466e87b76be170de3f881e3c14be52bf8eaa3b8c464dbeee3b4fef/vs_BuildTools.exe --output vs.exe
      - ./vs --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart --wait
      #- choco install visualstudio2019buildtools --ignore-package-exit-codes --package-parameters '--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart'
      - choco install python3 --params "/InstallDir:C:\Python37"
      - /c/Python37/python.exe -m pip install requests semantic_version lxml
      - /c/Python37/python.exe ci/qt_downloader windows desktop ${QT_VERSION} win64_msvc2017_64
      - cmake -DNXI_QT_ROOT=${PWD}/${QT_VERSION}/msvc2017_64 .
      - cmake --build . --target nxi_deploy --config Release
      - cd ${PWD}/${QT_VERSION}/msvc2017_64
      - windeployqt
      - windeployqt ${TRAVIS_BUILD_DIR}/bin/nxi
      - 7z a -r ${RELEASE_FILENAME} ./bin/*
    deploy:
      provider: releases
      api_key:
        secure: S2FAka4xQ6VMZnakdnfeBLHUqcefnHIAhnpnNuZi/3iOwDTGDHm6CbVf2LHhowRjY+5k2QcH7FiQQqC9aZYg556loC+0MnhO7WwDZbLpFJlhc86vI1howSdse+w/6VNE1bVCqQomDrVvNXKgQ3NHC74mDXV1vk8jCCpXqxJPpFVtifLcvlKCIqRH8C6pa7yFFxElTS392lpeX+WXcG15FUsmqXTDUD9MST+vCh31zxuBNRSrOBxcC/u7ZkFl74K9y0Qtqdk0nvCruMMI1ddkVfQhYS2cmfvvViRAng5QdJT+9SqwKNpVi9amdNjK8NJXgqCxrAqX1YqufRL1LLXTYiOnLsztfSLDJQYGjWtyl13Hcrc85B4cyXe8tjRBUa1iIWFQjH84GcJwKFHCfE9rFz2f0w9PrvooHeibZmYucpF8Bu3UX7sPvU3iSGNFMX1j74srwBQwdQBDhEbMUroSr8WASsXaD7kw1AJdTO26fAEJUopS0OB2o7h4ULBrs+Ud3jCu1QcGYdVX5J6mjRMDyO6f7mgcF9tZiSH9oIvQI6L2n+JRYRCmRoWYHxYMke86g0yRuaq+ltTAvcCsXp8Trzc1S72F3Vm3NxWhAOpJ8tCiECOFGarW5GUpS4rnw38kEbBmlwtYf8f9B+LpOuuf37/q7y+Lflh1heMAg0x3B2Y=
      file: ${RELEASE_FILENAME}
      skip_cleanup: true
      on:
        tags: true
        all_branches: true

  - os: osx
    osx_image: xcode11
    env:
      - QT_PATH=/usr/local/Cellar/qt/5.13.1
    before_install:
      - brew install qt5
      - brew link qt5 --force
      - brew install p7zip
      - ls /usr/local/Cellar/qt/
      - ls /usr/local/Cellar/qt/5.13.1
    script:
    - cmake -DNXI_QT_ROOT=${QT_PATH} -DSTZ_FILESYSTEM=ON .
    - cmake --build . --target nxi --config Release
    - 7z a -r ${RELEASE_FILENAME} ./bin/*
    deploy:
      provider: releases
      api_key:
        secure: S2FAka4xQ6VMZnakdnfeBLHUqcefnHIAhnpnNuZi/3iOwDTGDHm6CbVf2LHhowRjY+5k2QcH7FiQQqC9aZYg556loC+0MnhO7WwDZbLpFJlhc86vI1howSdse+w/6VNE1bVCqQomDrVvNXKgQ3NHC74mDXV1vk8jCCpXqxJPpFVtifLcvlKCIqRH8C6pa7yFFxElTS392lpeX+WXcG15FUsmqXTDUD9MST+vCh31zxuBNRSrOBxcC/u7ZkFl74K9y0Qtqdk0nvCruMMI1ddkVfQhYS2cmfvvViRAng5QdJT+9SqwKNpVi9amdNjK8NJXgqCxrAqX1YqufRL1LLXTYiOnLsztfSLDJQYGjWtyl13Hcrc85B4cyXe8tjRBUa1iIWFQjH84GcJwKFHCfE9rFz2f0w9PrvooHeibZmYucpF8Bu3UX7sPvU3iSGNFMX1j74srwBQwdQBDhEbMUroSr8WASsXaD7kw1AJdTO26fAEJUopS0OB2o7h4ULBrs+Ud3jCu1QcGYdVX5J6mjRMDyO6f7mgcF9tZiSH9oIvQI6L2n+JRYRCmRoWYHxYMke86g0yRuaq+ltTAvcCsXp8Trzc1S72F3Vm3NxWhAOpJ8tCiECOFGarW5GUpS4rnw38kEbBmlwtYf8f9B+LpOuuf37/q7y+Lflh1heMAg0x3B2Y=
      file: ${RELEASE_FILENAME}
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
