services: docker

matrix:
  include:
    - os: osx
      osx_image: xcode11
      before_install:
        - brew install qt5
        - brew link qt5 --force

      env:
        - QT_PATH=/usr/local/Cellar/qt/5.13.0


sudo: required

language:
  - cpp


script:
  - cmake -DCMAKE_PREFIX_PATH=${QT_PATH} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} .
  - cmake --build . --target nxi --config Release
