services: docker

matrix:
  include:
    - os: linux
      dist: bionic
      before_install:
        - docker build -t nxi ./ci
      script:
        - docker run -v $PWD:/nxi nxi
        - cmake -DNXI_QT_ROOT=${QT_PATH} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} .
        - cmake --build . --target nxi --config Release
      env:
        - CC=gcc-8 CXX=g++-8

  include:
    - os: osx
      osx_image: xcode11
      env:
        - QT_PATH=/usr/local/Cellar/qt/5.13.0
      before_install:
        - brew install qt5
        - brew link qt5 --force

        script:
        - cmake -DNXI_QT_ROOT=${QT_PATH} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DSTZ_FILESYSTEM=ON .
        - cmake --build . --target nxi --config Release


sudo: required

language:
  - cpp
